vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
        qgis_project:
            uri_prefix: /qgis
            upload_destination: '%kernel.project_dir%/public/qgis'
            # Will rename uploaded files using a uniqueid as a suffix.
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
